### ISSUE TITLE
uniapp cos post demo 抖音失败

### ISSUE THREAD

**Issue by z332406259** [tencentyun/cos-demo#11]
Error
>
<Code
>
MalformedPOSTRequest
</Code
>
<Message
>
The body of your POST request is not well-formed multipart/form-data.
</Message
>
<Resource
>
/
</Resource
>
<RequestId
>
NjQ0YTFkZDdfMTM0ZTQ0MGJfOTFiZV8zNzExOWNm
</RequestId
>
<TraceId
>
OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTI5MWRkM2I1ZDU3ZWE5Y2YzNDYzZTEzY2JlMjU3NDQ0ZDcwYzUyN2FkYjcxMmFjNjg5MGY0OWIyZWRlNDFhMGQ=
</TraceId
>
</Error>

抖音Tip：header 不支持设置 referer 、user-agent、content-type 字段字段

**Comment by carsonxu** [comment]
查不到错误原因。先关闭。
小程序应该都可以使用 PostObject 接口上传。
https://cloud.tencent.com/document/product/436/71469

**Comment by z332406259** [comment]
![image](https://github.com/tencentyun/cos-demo/assets/20322048/01e8e659-218c-4fac-b287-f02a218aba31)
<html>
<body>
<div class="shadow-split-widget-contents shadow-split-widget-sidebar vbox" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; position: relative; flex-direction: column; contain: size layout style; flex: 0 0 200px; border-top: 0px; border-right: 1px solid var(--divider-color); border-bottom: 0px; border-image: initial; border-left: 0px; color: rgb(213, 213, 213); font-family: &quot;Segoe UI&quot;, Tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="widget vbox brief-mode" id="network-container" slot="insertion-point-sidebar" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style; display: flex; flex-direction: column !important; border: 1px solid rgb(61, 61, 61); overflow: hidden;"><div class="vbox flex-auto split-widget" aria-hidden="false" style="--monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; position: relative; flex-direction: column !important; flex: 1 1 auto;"><div class="widget shadow-split-widget hbox" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style; display: flex; flex-direction: row !important; overflow: hidden;"><div class="shadow-split-widget-contents shadow-split-widget-main vbox maximized" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; position: relative; flex-direction: column; contain: size layout style; flex: 1 1 auto;"><div class="widget vbox" slot="insertion-point-main" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style; display: flex; flex-direction: column !important;"><div class="data-grid small network-log-grid data-grid-fits-viewport" tabindex="0" role="application" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; line-height: 14.4px; border: none !important; flex: 1 1 auto;"><div class="data-container" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: absolute; inset: 27px 0px 0px; overflow: hidden overlay; transform: translateZ(0px);">

dehui-1256972835.cos.ap-beijing.myqcloud.com
--
 

</div></div></div></div></div></div><div class="network-summary-bar toolbar" aria-hidden="false" style="flex: 0 0 27px; padding: 0px 2px 0px 5px; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; --accent-color: #4688f1; box-sizing: border-box; min-width: 0px; min-height: 0px; line-height: 27px; background-color: var(--toolbar-bg-color); border-top: 1px solid rgb(61, 61, 61); white-space: nowrap; text-overflow: ellipsis; overflow: hidden; user-select: text; border-bottom: 0px;"><div class="toolbar-shadow" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; white-space: nowrap; height: 26px; overflow: hidden; z-index: 12; display: flex; flex: 0 0 auto; align-items: center;"><div class="toolbar-text toolbar-item" aria-label="2 / 3 requests" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; display: flex; background-color: transparent; flex: 0 0 auto; align-items: center; justify-content: center; padding: 0px; height: 26px; border: none; white-space: pre; color: rgb(165, 165, 165); margin: 0px 5px;">2 / 3 requests</div><div class="toolbar-divider toolbar-item" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; display: flex; background-color: rgb(61, 61, 61); flex: 0 0 auto; align-items: center; justify-content: center; padding: 0px; height: 16px; border: none; white-space: pre; color: rgb(165, 165, 165); width: 1px; margin: 5px 4px;"></div><div class="toolbar-text toolbar-item" aria-label="1481 B / 6351 B transferred over network" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; display: flex; background-color: transparent; flex: 0 0 auto; align-items: center; justify-content: center; padding: 0px; height: 26px; border: none; white-space: pre; color: rgb(165, 165, 165); margin: 0px 5px;">1.5 kB / 6.4 kB transferred</div><div class="toolbar-divider toolbar-item" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; display: flex; background-color: rgb(61, 61, 61); flex: 0 0 auto; align-items: center; justify-content: center; padding: 0px; height: 16px; border: none; white-space: pre; color: rgb(165, 165, 165); width: 1px; margin: 5px 4px;"></div><div class="toolbar-text toolbar-item" aria-label="0 B / 4535 B resources loaded by the page" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; display: flex; background-color: transparent; flex: 0 0 auto; align-items: center; justify-content: center; padding: 0px; height: 26px; border: none; white-space: pre; color: rgb(165, 165, 165); margin: 0px 5px;">0 B / 4.5 kB resources</div><slot style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></slot></div></div></div></div><div class="shadow-split-widget-contents shadow-split-widget-main vbox" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; position: relative; flex-direction: column; contain: size layout style; flex: 1 1 auto; color: rgb(213, 213, 213); font-family: &quot;Segoe UI&quot;, Tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><slot name="insertion-point-main" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="widget vbox network-details-view" slot="insertion-point-main" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style; display: flex; flex-direction: column !important; background: rgb(62, 62, 62);"><div class="vbox flex-auto tabbed-pane network-item-view" style="--monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; position: relative; flex-direction: column !important; flex: 1 1 auto; background: var(--color-background);"><div class="widget vbox tabbed-pane-shadow" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style; display: flex; flex-direction: column !important;"><div class="tabbed-pane-header" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex: 0 0 27px; border-bottom: 1px solid rgb(61, 61, 61); overflow: visible; width: 605px; background-color: var(--toolbar-bg-color);"><div class="tabbed-pane-left-toolbar toolbar" style="flex: 0 0 auto; padding: 0px 2px; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; --accent-color: #4688f1; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-right: -4px;"><div class="toolbar-shadow" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; white-space: nowrap; height: 26px; overflow: hidden; z-index: 12; display: flex; flex: 0 0 auto; align-items: center;"><div is="dt-close-button" class="toolbar-item" style="--monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; display: flex; background-color: transparent; flex: 0 0 auto; align-items: center; justify-content: center; padding: 0px; height: 26px; border: none; white-space: pre; color: rgb(165, 165, 165); margin: 0px 5px;"><div class="close-button" aria-label="Close" role="button" style="box-sizing: border-box; min-width: 0px; min-height: 0px; width: 14px; height: 14px; cursor: default; display: flex; align-items: center; justify-content: center;"><span is="ui-icon" class="default-icon spritesheet-smallicons smallicon-cross" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: inline-block; flex-shrink: 0; background-position: var(--spritesheet-position); background-image: url(&quot;Images/smallIcons.svg&quot;); --spritesheet-position:-20px 70px; width: 10px; height: 10px;"></span></div></div><slot style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></slot></div></div><div class="tabbed-pane-header-contents" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; pointer-events: none; margin-left: 0px; position: relative;"><div class="tabbed-pane-header-tabs" role="tablist" style="box-sizing: border-box; min-width: 0px; min-height: 0px; pointer-events: initial;"><div class="tabbed-pane-header-tab" id="tab-headers" role="tab" aria-selected="false" aria-label="Headers" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: left; padding: 2px 0.8em; height: 26px; line-height: 16px; white-space: nowrap; cursor: default; display: flex; align-items: center; color: rgb(165, 165, 165); width: 63px;"><span class="tabbed-pane-header-tab-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px; text-overflow: ellipsis; overflow: hidden;">Headers</span></div><div class="tabbed-pane-header-tab selected" id="tab-preview" role="tab" aria-selected="true" aria-label="Preview" tabindex="0" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: left; padding: 2px 0.8em; height: 26px; line-height: 16px; white-space: nowrap; cursor: default; display: flex; align-items: center; color: var(--tab-selected-fg-color); border-bottom: none; background-color: var(--tab-selected-bg-color); width: 60px;"><span class="tabbed-pane-header-tab-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px; text-overflow: ellipsis; overflow: hidden;">Preview</span></div><div class="tabbed-pane-header-tab" id="tab-response" role="tab" aria-selected="false" aria-label="Response" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: left; padding: 2px 0.8em; height: 26px; line-height: 16px; white-space: nowrap; cursor: default; display: flex; align-items: center; color: rgb(165, 165, 165); width: 70px;"><span class="tabbed-pane-header-tab-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px; text-overflow: ellipsis; overflow: hidden;">Response</span></div><div class="tabbed-pane-header-tab" id="tab-initiator" role="tab" aria-selected="false" aria-label="Initiator" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: left; padding: 2px 0.8em; height: 26px; line-height: 16px; white-space: nowrap; cursor: default; display: flex; align-items: center; color: rgb(165, 165, 165); width: 61px;"><span class="tabbed-pane-header-tab-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px; text-overflow: ellipsis; overflow: hidden;">Initiator</span></div><div class="tabbed-pane-header-tab" id="tab-timing" role="tab" aria-selected="false" aria-label="Timing" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: left; padding: 2px 0.8em; height: 26px; line-height: 16px; white-space: nowrap; cursor: default; display: flex; align-items: center; color: rgb(165, 165, 165); width: 56px;"><span class="tabbed-pane-header-tab-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px; text-overflow: ellipsis; overflow: hidden;">Timing</span></div></div></div></div><div class="tabbed-pane-content" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; overflow: auto; flex: 1 1 auto; display: flex; flex-direction: column;"><slot style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="widget vbox request-view" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style; display: flex; flex-direction: column !important;"><div class="vbox flex-auto" style="--monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; position: relative; flex-direction: column !important; flex: 1 1 auto;"><div class="widget vbox" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style; display: flex; flex-direction: column !important;"><slot style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="vbox flex-auto" style="--monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; position: relative; flex-direction: column !important; flex: 1 1 auto;"><div class="widget shadow-xml-view source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; position: relative; flex: 1 1 auto; contain: style; user-select: text; overflow: auto; padding: 2px 4px;"><div style="flex: 1 1 auto; padding: 2px 0px 0px; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="tree-outline-disclosure" style="box-sizing: border-box; min-width: 100%; min-height: 0px; display: inline-block;"><ol class="tree-outline" role="tree" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; padding: 0px 0px 4px 4px; margin: 0px; z-index: 0; position: relative; list-style-type: none; padding-inline-start: 0px;"><li role="treeitem" class="parent selected expanded" aria-expanded="true" tabindex="0" aria-selected="true" style="box-sizing: border-box; min-width: 0px; min-height: 12px; text-overflow: ellipsis; white-space: nowrap; position: relative; display: flex; align-items: center; color: var(--selection-inactive-fg-color);"><div class="selection fill" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: absolute; inset: 0px; display: block; z-index: -1; margin-left: -10000px; background-color: var(--selection-inactive-bg-color);"></div><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;Error</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span></li><ol class="children expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style: none; padding: 0px; margin: 0px; padding-inline-start: 16px; display: block;"><li role="treeitem" style="box-sizing: border-box; min-width: 0px; min-height: 12px; text-overflow: ellipsis; white-space: nowrap; position: relative; display: flex; align-items: center;"><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;Code</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span><span class="shadow-xml-view-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(230, 230, 230); white-space: pre;">MalformedPOSTRequest</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;/Code</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span></li><li role="treeitem" style="box-sizing: border-box; min-width: 0px; min-height: 12px; text-overflow: ellipsis; white-space: nowrap; position: relative; display: flex; align-items: center;"><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;Message</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span><span class="shadow-xml-view-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(230, 230, 230); white-space: pre;">The body of your POST request is not well-formed multipart/form-data.</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;/Message</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span></li><li role="treeitem" style="box-sizing: border-box; min-width: 0px; min-height: 12px; text-overflow: ellipsis; white-space: nowrap; position: relative; display: flex; align-items: center;"><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;Resource</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span><span class="shadow-xml-view-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(230, 230, 230); white-space: pre;">/</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;/Resource</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span></li><li role="treeitem" style="box-sizing: border-box; min-width: 0px; min-height: 12px; text-overflow: ellipsis; white-space: nowrap; position: relative; display: flex; align-items: center;"><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;RequestId</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span><span class="shadow-xml-view-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(230, 230, 230); white-space: pre;">NjQ5MDExOWNfNDc0ZTQ0MGJfMWEyNmJfNGZmMjVkYg==</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;/RequestId</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span></li><li role="treeitem" style="box-sizing: border-box; min-width: 0px; min-height: 12px; text-overflow: ellipsis; white-space: nowrap; position: relative; display: flex; align-items: center;"><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;TraceId</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span><span class="shadow-xml-view-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(230, 230, 230); white-space: pre;">OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTI5MWRkM2I1ZDU3ZWE5Y2YzNDYzZTEzY2JlMjU3NDQ0ZDcwYzUyN2FkYjcxMmFjNjg5MGY0OWIyZWRlNDFhMGQ=</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;/TraceId</span><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&gt;</span></li><li role="treeitem" class="shadow-xml-view-close-tag" style="box-sizing: border-box; min-width: 0px; min-height: 12px; text-overflow: ellipsis; white-space: nowrap; position: relative; display: flex; align-items: center; margin-left: -16px;"><span class="shadow-xml-view-tag" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(237, 119, 229);">&lt;/Error&gt;</span></li></ol></ol></div></div></div></div></slot></div></div></div></slot></div></div></div></div></slot></div>
</body>
</html>

**Comment by z332406259** [comment]
使用官方的demo 上传文件的时候 因为抖音小程序 uploadfile 不支持修改header，所以它的默认content-type 为 multipart/form-data,然后cos post上传就会报错The body of your POST request is not well-formed multipart/form-data.   （抖音Tip：header 不支持设置 referer 、user-agent、content-type 字段字段），而如果是微信小程序上传就没有默认值所以就上传成功
![image](https://github.com/tencentyun/cos-demo/assets/20322048/218c555a-a600-4911-aae2-170b4f6762e9)

**Comment by z332406259** [comment]
@carsonxu
